// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int attemptsCounter = Integer.parseInt(args [0]);
		int lowerThanHalf = 0;
		int higherThanHalf = 0; 


		for (int i = 0; i < attemptsCounter; i++) {
			double randomNumber = Math.random();
			if (randomNumber > 0.5) {
				higherThanHalf += 1;
			} else {
				lowerThanHalf += 1;
			}

		}  
		System.out.println("> 0.5: " + higherThanHalf + " times");
		System.out.println("<= 0.5: " + lowerThanHalf + " times");
		
		if (higherThanHalf != 0 && lowerThanHalf != 0) {
			double ratio = (double) higherThanHalf / lowerThanHalf;
			System.out.println("Ratio: " + ratio );
	}

	}
}
